prices/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    path('', views.index, name='index'),
    path('changes/', views.changes, name='changes'),
    path('by_regions/', views.by_regions, name='by_regions'),
    path('by_regions/by_regions_update/', views.by_regions_update, name='by_regions_update'),
    path('changes/change_button/', views.change_button, name='change_button'),
    path('changes/save_price', views.save_price, name='save_price'),
    path('save_price', views.save_price, name='save_price'),
    path('change_date/', views.change_date, name='change_date'),
    path('export_prices/', views.export_prices, name='export_prices'),
    path('export_changes/', views.export_changes, name='export_changes'),
    path('export_by_region/', views.export_by_region, name='export_by_region'),
    path('changes/get_details/', views.get_details, name='get_details'),
]

prices/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
from datetime import timedelta


GROUP_CHOICES = (
    ('Food', 'Озиқ-овқат'),
    ('Non-food', 'Ноозиқ-овқат'),
    ('Service', 'Хизмат')
)


class Good(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, unique=True)
    weight = models.FloatField(max_length=255, validators=[MinValueValidator(0), MaxValueValidator(1)])
    description = models.CharField(max_length=255, null=True, blank=True)
    group = models.CharField(max_length=255, choices=GROUP_CHOICES)
    visible = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    order = models.PositiveIntegerField(unique=True, null=True)
    
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['order']


class Region(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, unique=True)
    population = models.FloatField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['id']


class Market(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default='Бозор')
    market_order =  models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(6)])
    is_market = models.BooleanField(default=True)

    class Meta:
        ordering = ['region_id', 'market_order']
        unique_together = ("region", "market_order")

    def __str__(self):
        return self.name


# actually to monday
def to_sunday():
    day = timezone.datetime.today()
    week_day = day.weekday()
    return day + timedelta(days=((7 if week_day else 0)-week_day))


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, blank=True, null=True)
    
    class Meta:
        ordering = ['region']  

    def __str__(self):
        return f'{self.user.first_name[0]}. {self.user.last_name}' if self.user.first_name else ''


class Price(models.Model):
    price = models.PositiveIntegerField(null=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    good = models.ForeignKey(Good, on_delete=models.CASCADE)
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    sunday = models.DateField(default=to_sunday)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    time = models.DateTimeField(default=timezone.datetime.now)

    class Meta:
        unique_together = ("region", "good", "market", "sunday")

    def __str__(self):
        return self.good.name


class MarketWeight(models.Model):
    good = models.ForeignKey(Good, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    weight = models.FloatField(max_length=32)

    class Meta:
        ordering = ['good', 'region']
        unique_together = ('good', 'region')

    def __str__(self):
        return f'{self.good}_{self.region}={self.weight}'


class SetDate(models.Model):
    date = models.DateField(default=to_sunday, null=True, blank=True)
    show_default = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'date'
        verbose_name_plural = 'Set date'

    def __str__(self):
        return self.date.strftime('%Y-%m-%d')


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    
    try:
        instance.profile.save()
    except ObjectDoesNotExist:
        Profile.objects.create(user=instance)

prices/forms.py
from django import forms

class Price_input(forms.Form):
    price = forms.IntegerField(label='', min_value=0)

class dataImportForm(forms.Form):
    xlsx_file = forms.FileField(
        label="Browse .xlsx file", 
    )

prices/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.utils import timezone

from .models import *
from .forms import Price_input, dataImportForm
from collections import defaultdict
from datetime import datetime
from io import BytesIO
from scipy.stats.mstats import gmean
import pandas as pd, numpy as np
import itertools, json


GROUP_NAMES = {
        'Food': "Озиқ-овқат маҳсулотлари",
        'Non-food': "Ноозиқ-овқат маҳсулотлар",
        'Service': "Хизматлар"
    }

CONTENT_TYPE_XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'


class TemplateIterator(itertools.count):
    def next(self):
        return next(self)


def add_style(table):
    s = table.index('<thead>')
    f = table.index('</thead>')
    changing = table[s:f].replace('<th>', '<th><span>').replace('</th>', '</span></th>')
    table = table[:s] + changing + table[f:]
    table = table.replace('dataframe', 'table table-bordered table-striped changes')
    table = table.replace('text-align: right;', 'text-align: center;')
    # table = table.replace('<td>', '<td onclick="alert(\'hi!\')">')
    return table


def get_market_weights(region_names, good_names):
    names = ["good_id__name", "region_id__name", "weight"]
    mar_weig_df = pd.DataFrame(MarketWeight.objects.values(*names))
    mar_weig_df.columns = ["good", "region", "weight"]

    mar_weig_df["region"] = mar_weig_df["region"].astype("category")
    mar_weig_df["region"].cat.set_categories(region_names, inplace=True)
    mar_weig_df["good"] = mar_weig_df["good"].astype("category")
    mar_weig_df["good"].cat.set_categories(good_names, inplace=True)

    market_weights = pd.pivot_table(mar_weig_df, index=["good"], columns=["region"], values=["weight"])
    return market_weights['weight']


def create_table_df(sana):
    names = ["good_id__name", "region_id__name", "market_id__name", "price", "sunday", "market_id__is_market"]
    prices_tb = Price.objects.filter(sunday=sana).values(*names)
    df = pd.DataFrame(prices_tb).dropna(subset=["price"])
    df.columns = ["good", "region", "market", "price", "sunday", "is_market"]
    regions = pd.DataFrame(Region.objects.all().values()).set_index('id')
    goods = pd.DataFrame(Good.objects.filter(visible=True).values())

    df["region"] = df["region"].astype("category")
    df["region"].cat.set_categories(regions["name"], inplace=True)
    df["good"] = df["good"].astype("category")
    df["good"].cat.set_categories(goods["name"], inplace=True)

    pt = pd.pivot_table(df, index=["good"], columns=["is_market", "region"], values=["price"], aggfunc=np.mean)
    prices = pt['price']
    filler = pd.DataFrame(index=pt.index, columns=prices.columns.get_level_values(1))
    market = prices.get(True, filler)
    supermarket = prices.get(False, filler).fillna(0)

    market_weights = get_market_weights(regions["name"], goods["name"])

    nonexisting_goods = [x for x in market_weights.index if x not in pt.index]
    if nonexisting_goods:
        market_weights.drop(nonexisting_goods, inplace=True)

    market_weights[supermarket == 0] = 1
    avrg_market = market.mul(market_weights, fill_value=0)
    avrg_supermarket = supermarket.mul(1-market_weights, fill_value=0).fillna(0)
    pt = avrg_market + avrg_supermarket
    only_vals = np.nan_to_num(pt.values)

    table_df = pd.DataFrame(only_vals, list(pt.index), list(pt.columns))
    region_weights = np.array(regions['population']/sum(regions['population']))
    table_df["Республика"] = np.dot(only_vals, region_weights)
    table_df = table_df[["Республика", *regions['name']]]
    return table_df


def sundays_list():
    sundays = sorted(set(Price.objects.values_list('sunday', flat=True)), reverse=True)
    return [(x.strftime('%Y-%m-%d'), x.strftime('%d-%m-%Y')) for x in sundays]

def keep_prices(x, is_old=False):
    only_prices = defaultdict(dict)
    r = defaultdict(lambda: defaultdict(list))
    for item in x:
        good = item['good_id']
        price = item['price']
        only_prices[good][item['market_id']] = price
        r[good][int(item['market_id__is_market'])].append(price) 
    
    if is_old:
        goods = Good.objects.filter(active=True).values_list('id', flat=True)
        for i in goods:
            if 0 not in r[i]:
                r[i][0] = []
            if 1 not in r[i]:
                r[i][1] = []
    return json.dumps(only_prices), json.dumps(r)


@login_required(login_url='login')
def index(request):
    if not request.user.is_staff:
        goods = Good.objects.filter(visible=True, active=True)
        regionId = request.user.profile.region_id
        markets = Market.objects.filter(region_id=regionId)
        market_weights = MarketWeight.objects.filter(region_id=regionId).values('good_id','weight')
        weights = { x['good_id']:x['weight'] for x in market_weights }
        is_market = { x['id']:int(x['is_market']) for x in markets.values() }
        market_indices = {}
        y = 0
        for m in markets.values():
            if (not m['is_market']) and y != 1:
                y = 0
            market_indices[m['id']] = y
            y = y + 1

        sana = SetDate.objects.get(id=1)
        sunday = to_sunday().date() if sana.show_default else sana.date

        sundays = sorted(set(Price.objects.values_list('sunday', flat=True)), reverse=True)
        if sunday in sundays:
            ind = sundays.index(sunday)
            old_sunday = sundays[ind + 1]
        else:
            old_sunday = sundays[0]

        region = Region.objects.get(id=regionId).name
        value_list = ['price','good_id','market_id','market_id__is_market']
        cur_prices = list(Price.objects.filter(region=regionId, sunday=sunday).values(*value_list))
        old_prices = list(Price.objects.filter(region=regionId, sunday=old_sunday).values(*value_list))
        only_prices, latter_prices = keep_prices(cur_prices, True)
        old_prices, former_prices = keep_prices(old_prices)

        context = {
            'goods':goods, 
            'markets':markets, 
            'region':region,
            'regionId':regionId,
            'sunday':sunday.strftime('%d-%m-%Y'),
            'my_form':Price_input(),
            'curr_prices':only_prices,
            'old_prices':old_prices,
            'former_prices':former_prices,
            'latter_prices':latter_prices,
            'weights':json.dumps(weights),
            'is_market':json.dumps(is_market),
            'market_indices':json.dumps(market_indices),
            'iterator':TemplateIterator(),
            'goods_len':len(goods),
            }
        return render(request, 'index.html', context)
    
    else:
        sundays = sundays_list()
        sunday = sundays[0][0]
        table_df = create_table_df(sunday)
        table = add_style(table_df.astype(int).to_html())
        context = {
            'data':table,
            'sana':sundays,
            'sunday':sunday
            }
        return render(request, 'results.html', context)


@login_required(login_url='login')
def save_price(request):
    if request.method == "POST":
        user = request.user
        req = request.POST
        price = req.get('price')
        time = req.get('time')
        if time is None:
            time = timezone.now()
        else:
            time = datetime.fromtimestamp(float(time))

        try:
            existing = dict(
                # region_id=user.profile.region_id,
                region_id=req.get('regionId'),
                good_id=req.get('goodId'),
                market_id=req.get('marketId'),
                sunday=timezone.datetime.strptime(req.get('sunday'), '%d-%m-%Y').date()
                )
            data = {
                'price': int(price) if price else None,
                'author_id': user.id,
                'time': time,
                }

            if price:
                Price.objects.update_or_create(**existing, defaults=data)
            else:
                Price.objects.filter(**existing).delete()
        
            return HttpResponse('')

        except Exception as err:
            print(err, flush=True)
            return HttpResponse(status=500)



@staff_member_required
def change_date(request):
    new_date = request.GET.get('date')
    table_df = create_table_df(new_date)
    table = add_style(table_df.astype(int).to_html())
    return HttpResponse(table)


def changes_table(former, latter):
    names = ["good_id__name", "region_id__name", "market_id__name", "price", 
            "sunday", "market_id__is_market", "good_id__group"]
    data = Price.objects.filter(sunday__in=[former,latter]).values(*names)
    df = pd.DataFrame(data).dropna(subset=["price"])
    df.columns = ["good", "region", "market", "price", "sunday", "is_market", "group"]

    regions = pd.DataFrame(Region.objects.all().values()).set_index('id')
    goods = pd.DataFrame(Good.objects.all().values()).set_index('name')
    df["region"] = df["region"].astype("category")
    df["region"].cat.set_categories(regions['name'], inplace=True)
    df["good"] = df["good"].astype("category")
    df["good"].cat.set_categories(goods.index, inplace=True)

    indices = ["sunday", "group", "good"]
    labels = ["is_market", "region"]

    former_dt = datetime.strptime(former, '%Y-%m-%d').date()
    latter_dt = datetime.strptime(latter, '%Y-%m-%d').date()

    df_nd = df.drop_duplicates(['good','sunday'], keep='last')
    goods_former = set(df_nd[df_nd['sunday']==former_dt]['good'])
    goods_latter = set(df_nd[df_nd['sunday']==latter_dt]['good'])
    goods_names = set(goods.index)
    union = goods_former | goods_latter | goods_names
    intersection = goods_former & goods_latter & goods_names
    # symmetric difference of 3 sets
    nonexisting_goods = union - intersection

prices/templates/add_js.html
{% extends 'admin/change_list.html' %}

{% block extrahead  %}
    {{ block.super }}
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script>
        const $ = django.jQuery;
        // ready(delay);
        // function ready(delay) {
        //     if (document.readyState != 'loading'){
        //         delay();
        //     } else {
        //         document.addEventListener('DOMContentLoaded', delay);
        //     }
        // }
        // function delay() {
        //     setTimeout(fn, 1000);
        // }
        // function fn() {
        //     var check_box = document.querySelector("input#id_form-0-show_default");
        //     var input_date = document.querySelector("#id_form-0-date");
        //     var calendar = document.querySelector("span.datetimeshortcuts");
        //     var sunday = '{{ sunday }}';
        //     if (check_box.checked === true) {
        //         input_date.value = sunday;
        //         input_date.setAttribute('disabled', 'disabled');
        //         calendar.style.display = 'none';
        //     }
        //     check_box.addEventListener('change', function(e) {
        //         if (event.target.checked === true) {
        //             input_date.value = sunday;
        //             // input_date.setAttribute('value', sunday);
        //             input_date.setAttribute('disabled', 'disabled');
        //             calendar.style.display = 'none';
        //         } else {
        //             input_date.removeAttribute('disabled');
        //             calendar.style.display = '';
        //         }
        //     });
        // }
        $(window).on('load', function() {
            var check_box = $("input#id_form-0-show_default");
            var input_date = $("#id_form-0-date");
            var sunday = '{{ sunday }}';
            var calendar = $("span.datetimeshortcuts");
            if (check_box.prop("checked") == true) {
                input_date.attr('value', sunday);
                input_date.attr('disabled', 'disabled');
                calendar.hide();
            }
            check_box.change(function() {
                if (this.checked) {
                    input_date.attr('value', sunday);
                    input_date.attr('disabled', 'disabled');
                    calendar.hide();
                } else {
                    input_date.removeAttr('disabled');
                    calendar.show();
                }
            });
        });
    </script>
{% endblock %}

prices/templates/base.html
<!doctype html>
<html lang="uz">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
      form{
        padding-top:2px;
      }
      #download_icon{
          height: 20px;
          cursor: pointer; 
          margin-bottom: 2px;
          margin-left: 2px;
          vertical-align: bottom;
      }
      .inline-block-child {
          display: inline-block;
      }
      .ajaxProgress {
          display: none;
          margin-bottom: 5px;
      }
    </style>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Weekly prices</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <!-- <a class="navbar-brand" href="">Ҳафталик нархлар</a> -->
      <span class="nav-item active">
        {{ request.user.first_name }} {{ request.user.last_name }}
      </span>
      <span><a href="{% url 'logout' %}">Чиқиш</a></span>
    </nav>
    <!-- <main class="container"> -->
      {% block prices_table %}
      {% endblock %}
    <!-- </main> -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

prices/templates/change_temp.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="import_excel_{{ model_name }}">Import data from Excel file</a>
    <br/>
    <br/>
    {{ block.super }}
{% endblock %}

prices/templates/index.html
{% extends 'base.html' %}

{% block prices_table %}
    <main class="container">
    <script>
        var weights = JSON.parse('{{ weights|safe }}');
        var is_market = JSON.parse('{{ is_market|safe }}');
        var market_indices = JSON.parse('{{ market_indices|safe }}');
        var curr_prices = JSON.parse('{{ curr_prices|safe }}');
        var old_prices = JSON.parse('{{ old_prices|safe }}');
        var lp = JSON.parse('{{ latter_prices|safe }}');
        var fp = JSON.parse('{{ former_prices|safe }}');
        var g, changes;
        // geometricMean
        function gm(arr) {
            let product = 1;
            let k = 0;
            for (let i = 0; i < arr.length; i++) {
                if (arr[i] != null) {
                    product = product * arr[i];
                    k++;
                }
            }
            return Math.pow(product, 1 / k);
        }
        //former market and supermarket, and latter ones, market weight
        function price_change(fm, fs, lm, ls, w, goodId) {
            let changed;
            const len_fm = len(fm); 
            const len_fs = len(fs); 
            const len_lm = len(lm); 
            const len_ls = len(ls);
            if (len_ls != 0 & len_lm != 0) {
                changed = (gm(lm)/gm(fm))**w * (gm(ls)/gm(fs))**(1-w);
            } else if (len_ls == 0 & len_lm == 0) {
                changed = 0;
            } else if (len_ls == 0) {
                changed = gm(lm)/gm(fm);
            } else {
                changed = gm(ls)/gm(fs);
            }
            const chan = $('tr#n_'+ goodId +' .new.detailed');
            const txt = changed == 0 ? 'x' : ((changed-1)*100).toFixed(1);
            chan.text(txt); //percent change
            //change color if market numbers are not the same
            if (len_fm + len_fs - len_lm - len_ls != 0 & changed != 0) {
                chan.addClass('nonmatch');
            } else {
                chan.removeClass('nonmatch');
            }
        }
        function len(array) {
            if (array != undefined) 
                return array.filter(x => x !== null).length;
            else 
                return 0;
        }
    </script>
    <style>
        #id_price{
            width: 100px;
        }
        td>p{
            margin-bottom: 0px;
        }
        div.container {
            max-width: 100%;
            height: 90vh;
            overflow: scroll;
            padding-left: 0px;
            margin-left: 0px;
        }
        thead th {
            position: sticky;
            top: 0;
        }
        tbody th {
            position: sticky;
            left: 0;
        }
        /* thead th:first-child {
            left: 0;
            z-index: 2;
        } */
        thead th.freeze {
            left: 0;
            z-index: 2;
        }
        thead th {
            background: #483D8B;
            color: #FFF;
            z-index: 1;
            text-align: center;
        }
        tbody th {
            background: #FFF;
            border-right: 1px solid #CCC;
            box-shadow: 1px 0 0 0 #ccc;
            margin-left: -100px;
        }
        .order {
            text-align: center;
        }
        table {
            border-collapse: collapse;
        }
        td, th {
            padding: 0.5em;
        }
        td {
            text-align: center;
        }
        .title {
            position: absolute;
            background: silver;
            padding: 4px;
            left: 12px;
            white-space: nowrap;
            font-weight: normal;
            font-size: 80%;
            /* top: 70%;
            max-width: 150%;
            display: block;
            word-wrap:break-word;
            white-space: normal;
            z-index: 5; */
        }
        #unsaved {
            font-size: 18px; 
            margin-top: 15px; 
            font-weight: bold;
            color:red;
            display:none;
        }
        .detailed:hover{
            cursor: pointer;
            color: blue;
            text-decoration: underline;
        }
        .nonmatch{
            background-color: red;
        }
    </style>
    <div id="unsaved">
        Сақланмаган нархлар: <span id="fails">0</span> та
    </div>
    <div style="font-size: 20px; margin-top: 15px; font-weight: bold;">
        <span style="float:left;margin-bottom: 15px">{{ region }}</span>
        <span style="float:right;margin-bottom: 15px">{{ sunday }}</span>
    </div>
    <div class="container">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="freeze">№</th>
                    <th class="freeze">Товар номи</th>
                    {% for market in markets %}
                        <th>{{ market.name }}</th>
                    {% endfor %}
                    <th class="freeze">Ўзгариши</th>
                </tr>
            </thead>
            <tbody>
                {% for good in goods %}
                    <tr id="n_{{ good.id }}">
                        <th class="new" class="order">{{ good.order }}</th>
                        <th class="new" title="{{ good.description }}" onclick="show_title(this)">
                            {{ good.name }}
                        </th>
                        {% for market in markets %}
                            {% with count=iterator.next %}
                                <td id="_{{ count }}">{{ my_form.as_p }}</td>
                                <script>
                                    var counts = "#_{{ count }} #id_price";
                                    $(counts).attr('tabindex', {{ good.order }} + {{ forloop.counter0 }} * {{ goods_len }});
                                    try {
                                        $(counts).val(curr_prices['{{ good.id }}']['{{ market.id }}']);
                                    } catch(e) {}
                                    $(counts).change(function () {
                                        var new_price = $(this).val();
                                        if (new_price < 0)
                                            $(this).css('background-color', 'red');
                                        else {
                                            $(this).removeAttr('style');
                                            save_price("#_{{ count }} #id_price", new_price, '{{ market.id }}', '{{ good.id }}');
                                        }
                                    });
                                </script>
                            {% endwith %}
                        {% endfor %}
                        <td class="new detailed" onclick="details('{{ good.id }}')"></td>
                        <script>
                            g = {{ good.id }};
                            price_change(fp[g][1], fp[g][0], lp[g][1], lp[g][0], weights[g], g);
                        </script>
                    </tr>
                    <tr class="old" id="r_{{ good.id }}" hidden>
                    {% for market in markets %}
                        <td id="m_{{ market.id }}"></td>
                        <script>
                        try {
                            $('tr#r_{{ good.id }} td#m_{{ market.id }}').text(old_prices['{{ good.id }}']['{{ market.id }}']);
                        } catch(e) {}
                        </script>
                    {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        {% comment %} document.addEventListener('keydown', function (event) {
            if (event.keyCode === 13 && event.target.nodeName === 'INPUT') {
                event.preventDefault();
                var input_id = event.target.parentNode.parentNode.id.replace('_','');
                var next_id = parseInt(input_id) + 1;
                try {
                    document.querySelector('#_' + next_id + ' input').focus();
                } catch(e) {
                    document.querySelector('#_0 input').focus();
                }
            }
        }); {% endcomment %}
        function save_price(el_id, price, marketId, goodId, is_failed, curr_time) {
            try {
                var arr = lp[goodId][is_market[marketId]];
                arr[market_indices[marketId]] = price!=0 ? Number(price) : null
                price_change(fp[goodId][1], fp[goodId][0], lp[goodId][1], lp[goodId][0], weights[goodId], goodId);
            } catch(e) {
                console.log("Cannot calculate change for: " + goodId);
            }

            is_failed = is_failed || false
            var context = {
                    'price': price,
                    'marketId': marketId,
                    'goodId': goodId,
                    'regionId': '{{ regionId }}',
                    'sunday': '{{ sunday }}',
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                }
            if (is_failed) 
                context['time'] = curr_time.getTime() / 1000;
            $.ajax({
                type: 'POST',
                url: 'save_price',
                data: context,
                success: function (data) {
                    if (is_failed) {
                        var fails = $("#fails");
                        var num_fail = fails.text();
                        fails.text(--num_fail);
                        $(el_id).removeAttr('style');
                        if (num_fail == 0) 
                            $("#unsaved").hide();
                    }
                },
                error: function(xhr, status, error){
                    if (xhr.status == 0) {
                        var fails = $("#fails");
                        var num_fail = fails.text();
                        fails.text(++num_fail);
                        $(el_id).css('background-color', 'yellow');
                        $("#unsaved").show();
                        var curr_time = new Date();
                        window.addEventListener("online", 
                            function() { save_price(el_id, price, marketId, goodId, true, curr_time); }, 
                            { once: true });
                    } else {
                        alert('Хатолик содир бўлди. Админга мурожаат қилинг! ' + xhr.status)
                    }
                }
            });
        };
        function show_title(el) {
            var $title = $(el).find(".title");
            if (!$title.length) {
                $(el).append('<span class="title">' + $(el).attr("title") + '</span>');
            } else {
                $title.remove();
            }
        };
        function details(good_id) {
            var row = '#r_' + good_id;
            var parent_row = 'tr#n_' + good_id + ' .new';
            if ($(row).is(":hidden")) {
                $(parent_row).attr("rowspan", "2");
                $(row).removeAttr("hidden");
            } else {
                $(parent_row).removeAttr("rowspan");
                $(row).prop("hidden", !this.checked);
            }
        }

        $("[tabindex]").addClass("TabOnEnter");
        $(document).on("keypress", ".TabOnEnter", function (e) {
        //Only do something when the user presses Enter
            if (e.keyCode == 13) {
                var nextElement = $('[tabindex="' + (this.tabIndex + 1) + '"]');
                if (nextElement.length)
                    nextElement.focus()
                else
                    $('[tabindex="1"]').focus();
            }
        });
    </script>
    </main>
{% endblock %}